//auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const LOAD_CHANNEL_LIST = 'LOAD_CHANNEL_LIST'

//channel
export const ADD_CHANNEL = 'ADD_CHANNEL'
export const SET_SELECTED_CHANNEL = 'SET_SELECTED_CHANNEL'
export const REMOVE_LOAD_CHANNEL_LIST = 'REMOVE_LOAD_CHANNEL_LIST'

//message

export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const LOAD_MESSAGES = 'LOAD_MESSAGES'